//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : train
//  @ File Name : TrainAdapter.java
//  @ Date : 2016/3/17
//  @ Author : 
//
//



package com.tarena.train.adapter;


public class TrainAdapter {
}
