//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : train
//  @ File Name : TrainEntity.java
//  @ Date : 2016/3/17
//  @ Author : 
//
//



package com.tarena.train.entity;


public class TrainEntity {
}
