//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : train
//  @ File Name : QueryActivity.java
//  @ Date : 2016/3/17
//  @ Author : 
//
//



package com.tarena.train.view;

import android.app.Activity;
import android.widget.Button;
import android.widget.EditText;


public class QueryActivity extends Activity{
	public EditText etStart;
	public EditText etEnd;
	public Button bt;
	
	public void oncreate() {
	
	}
	
	public void onDestroy() {
	
	}
}
