//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : train
//  @ File Name : QueryParser.java
//  @ Date : 2016/3/17
//  @ Author : 
//
//



package com.tarena.train.parser;

import java.util.ArrayList;

import com.tarena.train.entity.TrainEntity;


public class QueryParser {
	public ArrayList<TrainEntity> parser(String json) {
		return null;
	
	}
}
