//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : train
//  @ File Name : QueryBiz.java
//  @ Date : 2016/3/17
//  @ Author : 
//
//



package com.tarena.train.biz;


public class QueryBiz {
	public void query(String start, String end) {
	
	}
}
